### PR TITLE
Updated the Organization Readme

### PR DESCRIPTION
**Pull request by ayan-biswas0412**
I have updated the organization readme.

### CODE REVIEW

**Comment by ayan-biswas0412** [comment]
@manjotsidhu can you please review and merge it?
cc @CircuitVerse/issues-team

**Review by manjotsidhu — APPROVED** [review]

**Comment by ayan-biswas0412** [comment]
cc @CircuitVerse/circuitverse-core-team

**Review by gr455 — APPROVED** [review]
Looks good :tada:

**Review by Kartikay304 — APPROVED** [review]

**Comment by ayan-biswas0412** [comment]
can anybody please merge it?
cc @CircuitVerse/circuitverse-core-team

**Review by Palaksharma23 — APPROVED** [review]

**Pull request merged**
